### ISSUE TITLE
MunkiImporter does not work when using a Forced or Often profile

### ISSUE THREAD

**Issue by erikng** [autopkg/autopkg#301]
When configuring com.github.autopkg via a profile, some settings are respected but others are not. 

```The following recipes failed:
    AdobeFlashPlayer.munki
        MunkiImporter requires missing argument MUNKI_REPO```

You can work around this by setting the profile to Set-Once.

Per Greg's theory from yesterday:

```from Foundation import NSUserDefaults
NSUserDefaults.alloc().init().persistentDomainForName_('com.github.autopkg')```

This works for Set-Once, Often and Forced.

**Comment by erikng** [comment]
My apologies, but it turns out the original theory does not actually work. I did not properly test this yesterday.

**Comment by timsutton** [comment]
As far as I recall, I used `CFPreferencesCopyKeyList` so that we could pass arbitrary prefs set in `com.github.autopkg` into the the AutoPkg run env. At one point we had things like `MUNKI_REPO` hardcoded in AutoPkg core and wanted to decouple things so people could support additional "global defaults" for their own processors (like JSSImporter, etc.).

Maybe it could be possible to first ask `CFPreferencesCopyAppValue` for a given pref, if that will pick up preferences set with a Forced profile. The pref getting-and-setting code is simple and hasn't been touched in ages - the fact that it gets a list of all other pref keys and copies them into the env is the only thing that's perhaps a bit peculiar here.

**Comment by erikng** [comment]
If I'm understanding correctly, that would be useful for the `-k` flag? If so, makes perfect sense.

If CFPreferencesCopyAppValue could be usedm that would be great. I am working on a chef cookbook that can configure a set of recipes/overrides and then configure the autopkg preferences to match this.

I have it working, but someone could easily trample over the settings (intentionally or otherwise) by running any of the normal autopkg commands.

**Comment by timsutton** [comment]
No, it's actually so that you don't _have_ to use the `-k` flag to set additional prefs. For example, most people running Munki recipes will want the same value for `MUNKI_REPO`, so AutoPkg lets people define that via a `defaults write` at either the current-user or any-user domain. Previously we had a special case where we'd test for `MUNKI_REPO` and copy it into the env if it existed, but we wanted to not need to special-case anything for any additional processors. When I implemented this I didn't see any API to just copy the entire domain's pref keys into a dict, so it seemed necessary to first get the key list and copy over the values one by one.

**Comment by erikng** [comment]
Well just to add to this, I also discovered that if the plist is changed via some other mechanism (ex: change the profile payload via a set-once and delete the profile and reinstall) several aspects of autopkg won't work unless you do something to reread the preferences (ex: defaults read): repo-list, run etc. 

I've worked around the issue in chef but figured I should add some more details here.

**Comment by gregneagle** [comment]
https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/__init__.py#L401-L417

Perhaps this could be changed from:

```python
        for step in recipe["Process"]:
            try:
                processor_class = get_processor(step["Processor"],
                                                recipe=recipe, env=self.env)
            except (KeyError, AttributeError):
                msg = "Unknown processor '%s'." % step["Processor"]
                if "SharedProcessorRepoURL" in step:
                    msg += (" This shared processor can be added via the "
                            "repo: %s." % step["SharedProcessorRepoURL"])
                raise AutoPackagerError(msg)
            # Add arguments to set of variables.
            variables.update(set(step.get("Arguments", dict()).keys()))
            # Make sure all required input variables exist.
            for key, flags in processor_class.input_variables.items():
                if flags["required"] and (key not in variables):
                    raise AutoPackagerError("%s requires missing argument %s"
                                            % (step["Processor"], key))
```

to something like

```python
        for step in recipe["Process"]:
            try:
                processor_class = get_processor(step["Processor"],
                                                recipe=recipe, env=self.env)
            except (KeyError, AttributeError):
                msg = "Unknown processor '%s'." % step["Processor"]
                if "SharedProcessorRepoURL" in step:
                    msg += (" This shared processor can be added via the "
                            "repo: %s." % step["SharedProcessorRepoURL"])
                raise AutoPackagerError(msg)
            # Add arguments to set of variables.
            variables.update(set(step.get("Arguments", dict()).keys()))
            # Make sure all required input variables exist.
            for key, flags in processor_class.input_variables.items():
                if key not in variables:
                    # try to get any missing input variables from preferences/defaults
                    pref_value = CFPreferencesCopyAppValue(key, BUNDLE_ID)
                    if pref_value:
                        variables[key] = pref_value
                if flags["required"] and (key not in variables):
                    # if it's still missing and its required, raise an exception
                    raise AutoPackagerError("%s requires missing argument %s"
                                            % (step["Processor"], key))
```

I feel like I might be missing something here...

**Comment by erikng** [comment]
So that fixed `autopkg repo-list` but `autopkg run` is still broken. I'm sure other things are as well.

**Comment by gregneagle** [comment]
You are going to have to provide more examples and data and perhaps even describe your testing scenario. You have a very special idiosyncratic need (I think managing autopkg config via MCX/config profiles is/will be very uncommon) and we'll need solid, reproducible things if you want us to work on this.

Stuff like " `autopkg run` is still broken " isn't helpful or specific enough to do anything with.

Or _you_ can work on it and create a PR.

**Comment by erikng** [comment]
I'm going to go ahead and close this. Even with some testing that greg did, there are other things that are still broken and would need to be fixed; it's not worth the amount of effort to fix CoreProcessors, etc.
